### ISSUE TITLE
Treatment of cross-references to anchor vs page number

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#17] opened 2020-10-04 01:09 UTC
In the SI brochure there are cross references that use page numbers. We should use a consistent encoding for all cross references. The page number is required by the BIPM in printed versions.

However, these page numbers don't make sense in an HTML layout, so they need to generate differently in PDF vs HTML.

<img width="501" alt="Screen Shot 2020-10-04 at 9 07 49 AM" src="https://user-images.githubusercontent.com/11865/95004684-23d85680-0621-11eb-9f4d-f50812f85937.png">

From @opoudjis:
> The needed template for that is to put "see" before any cross-references, allow page numbers to trail after the cross-reference, and have uniform text for all cross-references.

We need to rephrase all crossreferences to match `see <<...>>`, where `<<...>>` can be:
* "Recommendation 2 (CI-2002) of the CIPM"; or
* "Recommendation 2 (CI-2002) of the CIPM, p. 182"

I've found these examples:

CGPM resolutions:
"26th CGPM in 2018 (Resolution 1, see p. 197)"
"1960 by the 11th CGPM (Resolution 6, see p. 164)."
"1954, the 10th CGPM (Resolution 6, see p. 163)"
"13th CGPM, 1967/68 (Resolutions 7 and 3, see pp. 170 and 169, respectively)"
"16th CGPM, 1979 (Resolution 6, see p. 174)”

CIPM recommendations
"Recommendation 1 (CI-2002) of the CIPM […] p. 181”
"(Recommendation 2, see p. 182)”
"Recommendation 5 (CI-1989, PV, 57, 115)"
"See Recommendation 2 (CI-2005)”
"Recommendation 1 (CI-1980)”
“(Recommendation 1 (CI-1997))”

**Comment by opoudjis** [comment] 2020-10-04 12:19
An additional issue:

Page numbers in the table of contents of Appendix 1 of the brochure are bare page numbers in PDF, and hyperlinks in HTML. So we need to allow two renderings of cross-references in PDF, whether they correspond to distinct source markup or not.

TOC:

`9^th^ CGPM, 1948:: decision to establish the SI`

Needs to turn into 

PDF:

`9^th^ CGPM, 1948<tab/> decision to establish the SI <tab/>  <b>50</b> `

HTML:

`9^th^ CGPM, 1948<tab/> decision to establish the SI <tab/><a href="">Annex A.1.1</a>`

The HTML in https://www.bipm.org/en/publications/si-brochure/appendix1.html currently does not look like that at all. But generating lots of tiny HTML files is not what Metanorma is set up to do.

**Comment by opoudjis** [comment] 2020-10-04 12:38
These cross references regrettably look nothing like the title of what they are referencing: the cross-references are in fact citations, with idiosyncratic reproduction of the cited material in appendix text.

So we need to extract `26th CGPM in 2018 (Resolution 1)` from the following:

````
== 26^th^ CGPM, 2018
  
=== On the revision of the International System of Units, the SI (CR, in press and Metrologia, 2019, 56, 022001)

[align=center]
*Resolution 1*
````

It looks like, idiosyncratically for this document, we need to skip the level 2 title ("On the revision of...") as a rubric, and generate the crossreference out of the level 1 title ("26^th^ CGPM, 2018") plus the level 3 title (`*Resolution 1*`), which is not currently a title at all.

**Comment by opoudjis** [comment] 2020-10-04 12:42
Therefore, editorial action needed:

* All resolutions and recommendations in the appendix to become distinct clauses, and targets of cross-references
* Cross-references introduced
* Text surrounding cross-references rewrtitten, per formats above

**Comment by ronaldtse** [comment] 2020-10-05 12:03
Have agreed with @opoudjis way forward.

**Comment by opoudjis** [comment] 2020-10-05 12:10
The way forward is as described above

**Comment by Intelligent2013** [comment] 2020-10-06 14:41
@opoudjis Agree.

**Comment by manuel489** [comment] 2020-10-07 00:44
> @manuel489, The way forward is...

PR added in https://github.com/metanorma/bipm-si-brochure/pull/23

**Comment by ronaldtse** [comment] 2020-10-07 01:54
Consistent presentation of cross-references within the document.

 
In Appendix 1, there are few patterns used to refer to resolutions/recommendations, for example:
 
CGPM resolutions:
* "26th CGPM in 2018 (Resolution 1, see p. 197)"                               
* "1960 by the 11th CGPM (Resolution 6, see p. 164)."                     
* "1954, the 10th CGPM (Resolution 6, see p. 163)"                           
* "13th CGPM, 1967/68 (Resolutions 7 and 3, see pp. 170 and 169, respectively)"              
* "16th CGPM, 1979 (Resolution 6, see p. 174)”                                   
 
CIPM recommendations:
* "Recommendation 1 (CI-2002) of the CIPM […] p. 181”
* "(Recommendation 2, see p. 182)”
* "Recommendation 5 (CI-1989, PV, 57, 115)"
* "See Recommendation 2 (CI-2005)”


## Solution

We need to differentiate between "cross-references in original resolution" and "cross-references in current context".

### Cross references in original resolutions

Text like these in the original resolutions should not be changed:

e.g.

* "Recommendation 1 (CI-1980)”
* “(Recommendation 1 (CI-1997))”
 

To make semantic referencing possible we will use a consistent mechanism across these references (at least for the ones that refer to page numbers).
 
### CGPM resolutions
 
Use this rendered text for a reference link:
* For PDF: “Resolution N, see p. NNN"
* For HTML: “Resolution N"

We need to of course keep the part of the citation before the parenthesis which identifies the particular CGPM meeting , e.g. “26th CGPM in 2018” for the first example. This part appears in different forms, “26th CGPM in 2018” or  “1960 by the 11th CGPM” because it is part of a complete sentence to the structure of which it has to adapt.

We want to keep the surrounding text of the sentence. The text in the parenthesis can be updated as proposed.

### CIPM decisions/recommendations

Use this rendered text for a reference link:
* For PDF: “Recommendation N (CI-YYYY), see p. NNN"
* For HTML: “Recommendation N (CI-YYYY)"

Again, we should not change the surrounding text

**Comment by ronaldtse** [comment] 2020-10-07 02:11
Ping @manuel489 according to the BIPM advice above, could you help update https://github.com/metanorma/bipm-si-brochure/pull/23 ? Thanks!

**Comment by opoudjis** [comment] 2020-10-12 12:17
@manuel489 can I confirm there is nothing further for me to do here? If so, I'll close the ticket.

**Comment by opoudjis** [comment] 2020-10-12 13:10
@Intelligent2013 Is work on this ticket finalised by you? If so, please close this ticket; if not, tell me what more you require.

**Comment by Intelligent2013** [comment] 2020-10-12 13:34
@opoudjis don't close, I'm working on it yet.

**Comment by Intelligent2013** [comment] 2020-10-12 15:20
>     * This will be rendered as `<xref target="cgpm26r1">26th CGPM in 2018 (Resolution 1)</xref>`.
> @Intelligent2013 You will need to insert the page number reference into that text, before the close parenthesis if present

@opoudjis I need a clarification for this point.

Source 
```adoc
<<cgpm26th2018r1,26^th^ CGPM (Resolution 1)>>
```

rendered as: 

```xml
 26<sup>th</sup> CGPM (<xref target="cgpm26th2018r1r1">Resolution 1</xref>)
```

instead of

```xml
<xref target="cgpm26th2018r1r1">26<sup>th</sup> CGPM (Resolution 1)</xref>
```

It is ok?

**Comment by ronaldtse** [comment] 2020-10-12 17:46
@Intelligent2013 yes it is okay, because we don't have a way of differentiating the generation of the `26^th CGPM (Resolution 1)` vs `26th CGPM in 2018 (Resolution 1)` etc.

**Comment by Intelligent2013** [comment] 2020-10-12 18:49
@ronaldtse thank you.

**Closed by Intelligent2013** 2020-10-12 18:49 UTC
Labels: enhancement
