### ISSUE TITLE
French SI Brochure showing broken reference

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#66] opened 2020-11-17 14:11 UTC
[si-brochure-fr.pdf](https://github.com/metanorma/metanorma-bipm/files/5553586/si-brochure-fr.pdf)

<img width="443" alt="image" src="https://user-images.githubusercontent.com/11865/99393450-4f38ab80-2918-11eb-8ae0-1ed30770a1ce.png">

**Comment by opoudjis** [comment] 2020-11-17 14:23
Duplicate of https://github.com/metanorma/metanorma/issues/146

**Closed by opoudjis** 2020-11-17 14:23 UTC
Labels: bug, duplicate
