### ISSUE TITLE
Create BIPM flavor, support document type "brochure"

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-bipm#1] opened 2020-09-03 11:35 UTC
Based on the SI Brochure layout:
https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf

**Comment by ronaldtse** [comment] 2020-09-15 22:56
Modeling completed at https://github.com/metanorma/metanorma-model-bipm

**Comment by opoudjis** [comment] 2020-09-21 11:21
Introducing configurable abbreviations of organisations in standoc

**Comment by opoudjis** [comment] 2020-09-21 14:19
Introduce configurable validation of committee values

**Comment by opoudjis** [comment] 2020-09-21 15:28
For internationalisation, need to allow configuration to be hash of languages to files

**Comment by opoudjis** [comment] 2020-09-22 12:07
Genuine internationalisation includes internationalisation of the display values of bibdata, but the original English values need to maintained for logic. Will need to allow translation of bibdata in presentation XML, and extract both original and display values for metadata.

**Comment by opoudjis** [comment] 2020-09-22 13:50
The i18n values (display values) for bibdata are in the local_bibdata element, which duplicates bibdata, but internationalises docstage, docsubstage, and doctype. @Intelligent2013 This is an update to Presentation XML.

**Comment by opoudjis** [comment] 2020-09-22 15:02
The boilerplate also needs to be localised

**Comment by opoudjis** [comment] 2020-09-23 01:04
Markup of the SI brochure needs to address the fact that included documents aren't being recognised as appendixes.

**Comment by Intelligent2013** [comment] 2020-09-23 07:15
**DRAFT** 
I'll put here a differences between original PDF and source metanorma XML data.
1. On 3rd page in PDF there are a titles with `(SI)` addon:
![изображение](https://user-images.githubusercontent.com/5559926/93978055-16e77780-fd84-11ea-891e-f4409de80f03.png)

but in XML there isn't `(SI)` in title:
```xml
<title language="en" format="text/plain" type="main">The International System of Units</title>
<title language="fr" format="text/plain" type="main">Le Système international d’unités</title>
```

On other pages in PDF also there isn't `(SI)`, see cover page and 8th page:
![изображение](https://user-images.githubusercontent.com/5559926/93978260-64fc7b00-fd84-11ea-8097-f0d1f3227aee.png)

2. On 5th page in PDF:
![изображение](https://user-images.githubusercontent.com/5559926/93978478-bc025000-fd84-11ea-8b8b-f41d0de8e3e0.png)

In XML:
```xml
<contributor>
<role type="author"/>
<organization>
<name>Bureau International de Poids et Mesures</name>
<abbreviation>BIPM</abbreviation>
</organization>
</contributor>
<contributor>
<role type="publisher"/>
<organization>
<name>Bureau International de Poids et Mesures</name>
<abbreviation>BIPM</abbreviation>
</organization>
</contributor>
```

There is a difference between caps and 'des' vs. 'de'.

3. On 5th page in PDF specified version number v1.07:
![изображение](https://user-images.githubusercontent.com/5559926/93978723-100d3480-fd85-11ea-80fb-456fca38cf75.png)
In xml there isn't.

4. In PDF, there is an indent between table number and table name:
![изображение](https://user-images.githubusercontent.com/5559926/93978849-4054d300-fd85-11ea-95c0-9792948d9336.png)

If we need to reproduce it in resulted PDF, then we need to separate them somehow in xml - add `<tab/>` or split them in different tags/attributes.
Current source xml:
```xml
<name>Tableau 1 — Les sept constantes définissant le SI et les sept unités qu’elles définissent</name>
```

**Comment by opoudjis** [comment] 2020-09-23 12:27
XML is missing type and version.

**Comment by opoudjis** [comment] 2020-09-23 13:16
(1) Added as `/bibdata/title[@type = 'cover']`

(2) Fixed

(3) Added to source as `/bibdata/version/draft`

(4) Fixed

(5) Added to boilerplate/license-statement, but genericised to "This document" (the "SI Brochure" title is not in fact the title of the document, and I see little justification to perpetuating idiosyncrasy.)

**Comment by opoudjis** [comment] 2020-09-23 13:28
Appendixes are numbered with arabic numerals, not letters.

**Comment by Intelligent2013** [comment] 2020-09-23 18:29
@opoudjis thank you.

6. In source PDF before the Contents pages there is a section:
![изображение](https://user-images.githubusercontent.com/5559926/94053574-29dd6480-fde3-11ea-9cd2-774acb800419.png)

and after the Content pages there is a section:

![изображение](https://user-images.githubusercontent.com/5559926/94053604-395cad80-fde3-11ea-8761-b6dee7e679cc.png)

but in source XML there sections placed all together in `/preface/abstract`. Here is example - the latest `p` for section 'before' Contents and the first 'p' for section 'after' Contents:
```xml
...
<p id="_8d11cbfb-90ac-499d-b38d-e9462181ac0f">Depuis 1965 la revue internationale <em>Metrologia</em>, éditée sous les auspices du Comité
international des poids et mesures, publie des articles sur la métrologie scientifique,
l’amélioration des méthodes de mesure, les travaux sur les étalons et sur les unités,
ainsi que des rapports concernant les activités, les décisions et les recommandations des
organes de la Convention du Mètre.</p>
<p id="_33d9c195-327b-4de1-96d2-ade72469a110">Depuis son établissement en 1960 par une résolution adoptée par la Conférence générale
des poids et mesures (CGPM) à sa 11<sup>e</sup> réunion, le Système international d’unités (SI) est
utilisé dans le monde entier comme le système préféré d’unités et comme le langage
fondamental de la science, de la technologie, de l’industrie et du commerce.</p>
...
```

**Comment by Intelligent2013** [comment] 2020-09-24 15:21
7. In the source PDF, sometimes the list numbering started not from 1:

![изображение](https://user-images.githubusercontent.com/5559926/94164391-a9c20800-fe91-11ea-83d9-8435cad346ac.png)

but in xml there isn't such meta data:
```xml
<ol id="_3286792b-2ebf-4a60-a9a6-87ae3f960de8" type="arabic">
<li>
<p id="_787bf896-9427-4a4c-abd3-658446f35be4">Les unités photométriques peuvent être définies comme suit:</p>
<dl id="_f275db51-1135-4e51-aac3-7bb4f253be1c">
<dt><strong><em>Bougie nouvelle</em></strong> (unité d’intensité lumineuse).</dt>
<dd>
<p id="_f99e6a8b-8747-4232-846b-0529748b3e86">La grandeur de la bougie nouvelle est telle
que la brillance du radiateur intégral à la température de solidification du platine soit de
60 bougies nouvelles par centimètre carré.</p>
</dd>
<dt><strong><em>Lumen nouveau</em></strong> (unité de flux lumineux).</dt>
<dd>
<p id="_0fd9e1d0-86d7-44e9-ab86-8ff4178fb784">Le lumen nouveau est le flux lumineux émis dans
l’angle solide unité (stéradian) par une source ponctuelle uniforme ayant une intensité
lumineuse de 1 bougie nouvelle.</p>
</dd>
</dl>
</li>
<li>
<p id="_69d002e9-366e-43b6-a14c-ba604baa8513">. . .</p>
</li>
</ol>
```

therefore in resulted PDF we have:
![изображение](https://user-images.githubusercontent.com/5559926/94164681-0291a080-fe92-11ea-87af-8e9304d93379.png)

I see two possible solutions:
1. Put full list item text in simple `p` like this:
```xml
<p>4. Les unités photométriques peuvent être définies comme suit :</p>
```
or

2. Add an attibute `start` for `ol` like this:
```xml
<ol id="_3286792b-2ebf-4a60-a9a6-87ae3f960de8" type="arabic" start="4">
<li>
<p id="_787bf896-9427-4a4c-abd3-658446f35be4">Les unités photométriques peuvent être définies comme suit:</p>
```

**Comment by opoudjis** [comment] 2020-09-24 15:51
(6) Fixed markup, differentiated preface as prefatory clause.

**Comment by opoudjis** [comment] 2020-09-24 15:59
(7) This will be a separate ticket: https://github.com/metanorma/metanorma-standoc/issues/349

**Comment by opoudjis** [comment] 2020-09-25 14:17
Not proceeding with (7), changed markup.

**Comment by opoudjis** [comment] 2020-09-26 03:24
metadata_extensions config in YAML needs to permit nested elements

**Comment by opoudjis** [comment] 2020-09-26 14:31
Am needing to deal with this in isodoc/metadata, so will output /bibdata/ext/ to a Hash: https://stackoverflow.com/a/10144623

**Comment by Intelligent2013** [comment] 2020-09-28 17:01
8. Annex I in source PDF contains a `Table des matières de l’annexe 1`. I don't figure out how to display it in PDF. Looks like should be added some additional meta-information into XML.
![изображение](https://user-images.githubusercontent.com/5559926/94461627-0c354400-01c3-11eb-8097-f638fe479024.png)

8.1. The items group by catetegory.
8.2. The title contains only part of title from document body:
From table of contents:
![изображение](https://user-images.githubusercontent.com/5559926/94461999-89f94f80-01c3-11eb-8cc0-cb2c8de213e0.png)
From document body:
![изображение](https://user-images.githubusercontent.com/5559926/94462071-a5645a80-01c3-11eb-9ed9-427602d7e7f4.png)
8.3. Source xml contains 2nd and 3rd level section's numbers. Should I ignore it and show 'quad' character instead of 3rd level number?
For example,
original PDF:
![изображение](https://user-images.githubusercontent.com/5559926/94462236-dfcdf780-01c3-11eb-8434-f37aa71652e4.png)

current resulted PDF:
![изображение](https://user-images.githubusercontent.com/5559926/94462447-32a7af00-01c4-11eb-8f38-518ab6c02f4f.png)


9. Some text on the page sides in Annexes looks as 'footnotes, i.e. there is 'mark' like '*' in the text body  and the notes starts with the mark also, see `*` and `**`:
![изображение](https://user-images.githubusercontent.com/5559926/94462964-edd04800-01c4-11eb-89fd-4500bf5168b7.png)

But in the source XML it determined as `note`s:
```xml
<ol id="_ef59d0ec-5c54-4114-9f96-d0c10c17b50c" type="arabic">
<li>
<p id="_42ac29b0-1e59-4747-acb6-821578b2d679">Le kilogramme est l’unité de masse; il est égal à la masse du prototype international du
kilogramme;</p>
<note id="_eb31e25d-43c8-4d2d-be6a-aa6edef8b32e"><name>NOTE  1</name>
<p id="_56f20fe6-057f-4b2c-8222-d5fa162299d6">Définition abrogée en 2018 par la CGPM
à sa 26<sup>e</sup> réunion (Résolution 1, <em>voir</em> p.92).</p>
</note>
</li>
<li>
<p id="_2b2a73c0-8cdd-448c-a5f0-2afa54914a6d">Le terme poids désigne une grandeur de la même nature qu’une force; le poids d’un corps
est le produit de la masse de ce corps par l’accélération de la pesanteur;
en particulier, le poids normal d’un corps est le produit de la masse de ce corps par
l’accélération normale de la pesanteur;</p>
</li>
<li>
<p id="_32f0948f-9ccf-4165-93c1-809a114a6e98">Le nombre adopté dans le Service international des Poids et Mesures pour la valeur de
l’accélération normale de la pesanteur est <stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><mn>980</mn><mi>,</mi><mn>665</mn></math></stem> <stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><msup><mrow><mtext>cm/s</mtext></mrow><mrow><mn>2</mn></mrow></msup></math></stem>, nombre sanctionné déjà par
quelques législations.</p>
<note id="_79d8da3a-e3e1-47e3-8ef7-723ca172159f"><name>NOTE  2</name>
<p id="_cd6025e3-e374-4a14-ba84-218ed5af13e3">Cette valeur de <stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><msub><mrow><mi>g</mi></mrow><mrow><mtext>n</mtext></mrow></msub></math></stem> est la valeur conventionnelle de
référence pour le calcul de l’unité kilogramme-force
maintenant abolie.</p>
</note>
</li>
</ol>
```

**Comment by Intelligent2013** [comment] 2020-09-28 21:41
10. In source PDF there is a text `Remarque`:
![изображение](https://user-images.githubusercontent.com/5559926/94488804-f8ea9e80-01eb-11eb-936a-30e13a123d8c.png)
which coded in XML as `note`:
```xml
<li>
<p id="_80b89e67-6dc9-425a-96aa-d27928740749">mettre à jour la fréquence de la transition suivante dans la liste des fréquences étalons
recommandées et l’approuver comme représentation secondaire de la seconde:</p>
<ul id="_85f8ccf8-fb70-47f5-bee9-7a6e40b32324">
<li>
<p id="_1ede75c4-875f-409f-9119-3013b050d10c">la transition quantique hyperfine non perturbée de l’état fondamental de l’atome de
<sup>87</sup>Rb, à la fréquence de <stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><mn>6</mn><mtext> </mtext><mn>834</mn><mtext> </mtext><mn>682</mn><mtext> </mtext><mn>610.904</mn><mtext> </mtext><mn>312</mn><mtext> Hz</mtext></math></stem> avec une incertitude-type
relative estimée de <stem type="MathML"><math xmlns="http://www.w3.org/1998/Math/MathML"><mn>1</mn><mi>,</mi><mn>3</mn><mo>×</mo><msup><mrow><mn>10</mn></mrow><mrow><mrow><mo>−</mo><mn>15</mn></mrow></mrow></msup></math></stem>.</p>
<note id="_852fee6c-91d1-4f0a-be10-a2263cb7c2e1"><name>NOTE  2</name>
<p id="_193943b0-74b4-47a1-ac59-cb7d5b36999f">La valeur de l’incertitude-type est supposée correspondre à un niveau de confiance
de 68 %. Toutefois, étant donné le nombre très limité de résultats disponibles, il se peut que,
rétrospectivement, cela ne s’avère pas exact.</p>
</note>
</li>
</ul>
</li>
</ul>
```

In BIPM xslt `note` tag is using for page sides notes (at right edge of page). 'Remarque' text should be encoded something else, or we need to determine a rules, when we put note in text, and when at page edge.

**Comment by opoudjis** [comment] 2020-09-29 04:42
(8.1, 8.2) The ToC is clearly not an automatically generated ToC. IMO we should leave it as text, but the page number references will need to be replaced with cross-references in the source markup.

(8.3) The section numbers must be retained for HTML, because page numbers in crossreferences for the HTML are meaningless, and the HTML should cross-reference something. (It could do so without an overt anchor text, but that would involve too much fiddling with the source markup to be reasonable.) For the PDF, therefore, the brochure (and at this stage only the brochure) should indeed ignore subsection numbers in Annexes.

(9, 10) There won't be any rules. In my opinion we are going to have to do a mix of:

* an attribute indicating that this Note or Example is to be rendered as a sidebar (if there is no asterisk)
* a footnote with an attribute indicating that it is to be rendered as a sidebar (if there is an asterisk)

**Comment by ronaldtse** [comment] 2020-09-29 18:22
How are these "block notes" encoded then?
<img width="565" alt="image" src="https://user-images.githubusercontent.com/11865/94599767-7e8d4d80-02c3-11eb-860c-7fdfc9d474af.png">

As normal notes too?

**Comment by ronaldtse** [comment] 2020-09-30 02:00
I have sought clarification from BIPM for 8.1/8.2 and 9/10.

**Comment by ronaldtse** [comment] 2020-09-30 16:14
From BIPM: 

> (8.1, 8.2) The ToC is clearly not an automatically generated ToC. IMO we should leave it as text, but the page number references will need to be replaced with cross-references in the source markup.

Let's encode the ToC as normal text.

>(9, 10) There won't be any rules. In my opinion we are going to have to do a mix of:
> How are these "block notes" encoded then?

These notes are "table notes" they apply to the table immediately above, and therefore are not side notes.

Ping @manuel489 to fix the source, and @opoudjis @Intelligent2013 .

**Comment by Intelligent2013** [comment] 2020-09-30 17:19
8.3. Fixed in xslt:
![изображение](https://user-images.githubusercontent.com/5559926/94718276-32d9b300-035a-11eb-803d-47acd87dfece.png)

**Comment by Intelligent2013** [comment] 2020-09-30 17:36
8.3. Fixed in xslt:
![изображение](https://user-images.githubusercontent.com/5559926/94719872-6ae1f580-035c-11eb-9232-2a2acf89b9b6.png)

**Comment by Intelligent2013** [comment] 2020-09-30 17:45
> These notes are "table notes" they apply to the table immediately above, and therefore are not side notes.

In source PDF there is a case, when side notes relates to the table:

![изображение](https://user-images.githubusercontent.com/5559926/94720269-eb085b00-035c-11eb-8607-4a4688d0be68.png)


We should definite exactly what does mean 'table notes'. In my opinion In terms of XML it means:
```xml
...
</tr>
</tbody>
<note .... </note>
</table>
```

I put all `<note>`s as side notes (except `preface` section).

When we should put notes as side notes and when 'table notes'?

**Comment by ronaldtse** [comment] 2020-09-30 17:49
I don’t remember exactly but there is a differentiation between a note and a table note. Perhaps @opoudjis can answer better.

**Comment by manuel489** [comment] 2020-09-30 17:57
> These notes are "table notes" they apply to the table immediately above, and therefore are not side notes.

@ronaldtse , I believe the source already have the correct markup about the table notes, which is:

````
...

| bar | stem:["bar"] | stilb | stem:[sf "sb"]
| hour | stem:["h"] | |
|===

NOTE: The symbols whose unit names are preceded by dots are those which had already been adopted by a decision of the CIPM.

NOTE: The symbol for the stere, the unit of volume for firewood, shall be "st" and not "s", which had been previously assigned to it by the CIPM.

NOTE: To indicate a temperature interval or difference, rather than a temperature, the word "degree" in full, or the abbreviation "deg", must be used.
````

Maybe, necessary changes have to be done in the yaml files.

**Comment by ronaldtse** [comment] 2020-10-02 02:06
@manuel489 thanks. @opoudjis are the table notes typically encoded as normal notes?

**Comment by opoudjis** [comment] 2020-10-02 02:32
Yes

**Comment by opoudjis** [comment] 2020-10-02 03:17
Table notes are notes within a `<table>`, so they should be being rendered in XML as @Intelligent2013 expects them to be. I will need to debug why they aren't being so treated.

**Comment by opoudjis** [comment] 2020-10-02 03:19
@ronaldtse:

https://user-images.githubusercontent.com/5559926/94488804-f8ea9e80-01eb-11eb-936a-30e13a123d8c.png 
 
This block note is not a table note nor a side note.

**Comment by opoudjis** [comment] 2020-10-02 10:20
This discussion thread is becoming quickly unmanageable. I am moving discussion of notes to a new ticket: https://github.com/metanorma/metanorma-bipm/issues/15

**Comment by opoudjis** [comment] 2020-10-02 11:01
I have also posted https://github.com/metanorma/metanorma-bipm/issues/16 separately.

**Comment by opoudjis** [comment] 2020-10-02 11:14
(11) The treatment of cross references in the existing HTML and PDF is clearly manually generated and inconsistent, and we should not be seeking to replicate it:

https://www.bipm.org/en/CGPM/db/17/2/

HTML: See **Recommendation 1 (CI-2002)** of the CIPM on the revision of the practical realization of the definition of the metre.
PDF: See Recommendation 1 (CI-2002) of the CIPM on the revision of the practical realization of the definition of the metre, p. 181.

https://www.bipm.org/en/CIPM/db/1984/1/

HTML: The CIPM, in 2002, decided to change the explanation of the quantity dose equivalent in the SI Brochure (**Recommendation 2**).
PDF: * The CIPM, in 2002, decided to change the explanation of the quantity dose equivalent in the SI Brochure (Recommendation 2, see p. 182).

In the first instance, the page reference is appended to the end of the paragraph; in the second, it is inserted with a "see" within the cross-reference. The first instance cannot be generated sensibly from a single Asciidoctor cross-reference, and we should  not seek to: markup should be adjusted so as to give sensible results in both PDF and HTML. The needed template for that is to put "see" before any cross-references, allow page numbers to trail after the cross-reference, and have uniform text for all cross-references.

* `See <<ci-2001-r2>> on the revision of the practical realization of the definition of the metre.`
  * HTML:  `See **Recommendation 2 (CI-2002) of the CIPM** on the revision of the practical realization of the definition of the metre.`
  * PDF: `See **Recommendation 2 (CI-2002) of the CIPM, p. 181** on the revision of the practical realization of the definition of the metre.`
* `The CIPM, in 2002, decided to change the explanation of the quantity dose equivalent in the SI Brochure (<<ci-2002-r2>>).`
  * HTML: `The CIPM, in 2002, decided to change the explanation of the quantity dose equivalent in the SI Brochure (**Recommendation 2 (CI-2002) of the CIPM**).`
  * PDF: `The CIPM, in 2002, decided to change the explanation of the quantity dose equivalent in the SI Brochure (**Recommendation 2 (CI-2002) of the CIPM, p. 182**).`

**Comment by opoudjis** [comment] 2020-10-04 12:43
(11) is now distinct ticket #17

**Closed** 2020-10-11 09:49 UTC
Labels: enhancement
